//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BefunDebug.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BefunDebug.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vvv:           &lt;           &lt;
        ///1&gt; 1+:::3/3*-!#^_&gt;::5/5*-!#^_v
        ///1$v          &gt;# v#      &gt;# v#&lt;
        ///1 &gt;:5558***-!|v$&lt;&gt;+\:1-!|v$&lt;
        ///&gt;^           &lt;&gt;$$^\     &lt;&gt;.@.
        /// </summary>
        internal static string Euler_Problem_001 {
            get {
                return ResourceManager.GetString("Euler_Problem_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v&gt;v&gt;ppp 0&gt;&gt;$ 10g20g:10p+:v
        ///202 &gt;00p0^|-*2/2::&lt;  vp02&lt;
        ///0::0^+ g00&lt;v**&quot;}P  &quot;:&lt;
        ///:1&gt;^@$.g00&lt;&gt;*` #v_^
        ///&gt;^        ^     &lt;.
        /// </summary>
        internal static string Euler_Problem_002 {
            get {
                return ResourceManager.GetString("Euler_Problem_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89197939490919v          &gt;00g10g1-:10p%#v_10g:30p1-40pv
        ///v+*29191929891&lt;          ^    &lt;         &lt;_v#!  %g04g03&lt;
        ///&gt;*+*+*+*+*+*+*v &gt;&quot;{.i &quot;+**10p#^ #p #0 #0 &lt;&gt;40g:1-40p2-|
        ///              &gt;#^ +# *# +# *# +# *# +# *# +#    &lt;@.g03&lt;.
        /// </summary>
        internal static string Euler_Problem_003 {
            get {
                return ResourceManager.GetString("Euler_Problem_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:010:pp5558***04p&gt;10g1+::10p04g-00g \#v_1+:00p\$1:10p\:04g- #v_$$03g.@
        ///                  ^         v $&lt;       &gt;1# 0# 1# p# *# :# v#  &lt;
        ///   v_v#-g1-g20g10g 1g20&lt;p201&lt;v_^#:/+55p10+1g10p1g10%+55:  &lt;
        ///   $ &gt;02g1+:02p 01 g - |     &gt;                            ^
        ///   &gt;              ^    &gt;:03g\`#v_03pv
        ///                  ^           $&lt;   0&lt;.
        /// </summary>
        internal static string Euler_Problem_004 {
            get {
                return ResourceManager.GetString("Euler_Problem_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45*00p110p120p &gt;10g20g*10p00g20g1+:20p`#v_10g.@ 
        ///               ^_v#`g00p03+1:g03   &lt;p031&lt;         v &lt;
        ///                 &gt;10g30g%          |1              &lt;^        p01/g03g01&lt; 
        ///                                   &gt;10g30g/40p150p  &gt; 20g50g1+:50p` #v_^
        ///                 ^                                &lt; |!%g05g04        &lt;
        ///                                                   ^&lt;.
        /// </summary>
        internal static string Euler_Problem_005 {
            get {
                return ResourceManager.GetString("Euler_Problem_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;d&quot;10p000p&gt;10g:00g+00p1-:#v_$010p&gt;&quot;c&quot;10g::1+:*\:5:+%\5:+/6+p`#v_       v
        ///&gt;$.@      ^            p01&lt;      ^                   p01+1g01 &lt;        0
        ///     &gt;                                   v
        ///|!:\&lt;|p01-1:g01&lt;$$_v#!:g+6/+:5\%+:5:g01 :&lt; p01&quot;c&quot;+&lt;_v#!p01:-1g01&lt;p01:g0&lt;
        ///\   ^&lt;             &gt;` &gt;                 #v_v
        ///&gt;         v            v-g+6/+:5\%+:5:g01&lt;          &gt;00g        ^
        ///##########&gt;                                       ^
        ///##########             &gt;010g:5:+%\5:+/6+pv
        ///##########                           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_006 {
            get {
                return ResourceManager.GetString("Euler_Problem_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v     // Project Euler - Problem 7
        ///############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_007 {
            get {
                return ResourceManager.GetString("Euler_Problem_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;v&quot;00p54*:10p552**:20p*30p85+40p050p060p070p080p    v
        ///&gt;150g60p&gt;60g:20g%\20g/9+g&quot;0&quot;-*60g1+:60p50g-40g-#v_:80g`#v_$&gt;50g1+:50p30g-#v_ 970p &gt;70g0g86*+,70g8-40g-#v_&quot;=&quot;,80g.@
        ///        ^                                       &lt;   $      ^                                                       &lt;
        ///                                                        &gt;80p060p&gt;60g50g+:2 0g%\20g /9+g&quot;0&quot;-60g9+0p60g1+ :60p40g-#v_^
        ///^                                                   &lt;                     &lt;       ^p07+1g07            &lt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_008 {
            get {
                return ResourceManager.GetString("Euler_Problem_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;d&quot;5:+*00p210p&gt;   120p&gt;v                &gt;20g1+:20p10g-#v_10g1+:10p00g-#v_ @
        ///                      ^                                &lt;
        ///              ^                                                        &lt;
        ///v                      &lt;                 
        ///&gt;20g:*10g:*+:30p0&gt;::*30g-#v_:30p20g10g++ 00g-#v_20g:.&quot; &quot;,10g:.&quot; &quot;,30g:.&quot;=&quot;,**.@
        ///                 |-g00 :+1&lt;                   
        ///                 &gt;$$                    ^    $&lt;.
        /// </summary>
        internal static string Euler_Problem_009 {
            get {
                return ResourceManager.GetString("Euler_Problem_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v     // Project Euler - Problem 10
        ///########################################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_010 {
            get {
                return ResourceManager.GetString("Euler_Problem_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v             v                                             &lt;
        ///&gt;&quot;4&quot;2/:*1-00p &gt; 000g: &quot;4&quot;2/ %&quot;?&quot;+\ &quot;4&quot;2/ /1+ p  00g:1-00p  #^_v++++++++++++++++++++++++++
        ///                                                               ++++++++++++++++++++++++++
        ///                                                               ++++++++++++++++++++++++++
        /// 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 | +++####################+++
        /// 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 | +++################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_011 {
            get {
                return ResourceManager.GetString("Euler_Problem_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v     // Project Euler - Problem 12
        ///
        ///
        ///####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_012 {
            get {
                return ResourceManager.GetString("Euler_Problem_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v     // Project Euler - Problem 13
        ///      37107287533902102798797998220837590246510135740250
        ///      46376937677490009712648124896970078050417018260538
        ///      74324986199524741059474233309513058123726617309629
        ///      91942213363574161572522430563301811072406154908250
        ///      23067588207539346171171980310421047513778063246676
        ///      89261670696623633820136378418383684178734361726757
        ///      28112879812849979408065481931592621691275889832738
        ///      44274228917432520321923589422876796487670272189318
        ///      47451 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_013 {
            get {
                return ResourceManager.GetString("Euler_Problem_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v               &gt;3*1+v
        ///&gt;0::p3&gt;1+:1\&gt;:2%|    &gt;\1+\:1- #v_$:00g\`#v_00p:10pv
        ///v:0.g0 1&lt;   ^  $&gt;# 2/^#1       &lt;         $
        ///g     ^_^#!`  **&quot;}}@&quot;:                   &lt;        &lt;
        ///&gt;&quot;: &quot;,,.@
        ///.
        /// </summary>
        internal static string Euler_Problem_014 {
            get {
                return ResourceManager.GetString("Euler_Problem_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// 000000000000000000000                                  
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_015 {
            get {
                return ResourceManager.GetString("Euler_Problem_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000001
        ///
        ///&gt; &quot;0&quot;:::::00p01p02p03p04p05p v  // INIT
        ///v  p64*8&quot;}&quot;p60*p62:6p61:&quot;&lt;&quot;  &lt;v p66-1g66                &lt;
        ///       &gt;06g1-66p             0&gt; 66g16g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_016 {
            get {
                return ResourceManager.GetString("Euler_Problem_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///033544355436688779886
        ///0366555766
        ///$
        ///$   v-1           &lt;    v-1          &lt;
        ///&gt;54*&gt;:::1g&quot;0&quot;-\1p#^_54*&gt;:::2g&quot;0&quot;-\2p|
        ///v                       **25&quot;d&quot; 0 $$&lt;
        ///v                                              &lt;
        ///   v            $&lt;   &gt;:55+/2g\55+%           v
        ///:              &gt;:54*`|         &gt;&quot;d&quot;/1g70     v
        ///&gt;0\&gt;:!#v_:&quot;d&quot;\`| ^0g1&lt;  &gt;:&quot;d&quot;%!|        v    &lt;
        ///v      &lt;       &gt;:&quot;}&quot;8*-#^_$380v&gt;:&quot;d&quot;/1g\ &quot;d&quot;%v
        ///   ^                          &lt;         &lt;\3\7&lt;
        ///&gt;+# \:# _+          \ 1-                      :|
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_017 {
            get {
                return ResourceManager.GetString("Euler_Problem_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &gt;53* 00p00g1-20p010p&gt;10g3*:20g1+g&quot;0&quot;-55+*\1+20g1+g&quot;0&quot;-+10g20g1+p10g1+:10p20g-1-#v_20g:1-20p010p#v_v
        ///75                    ^                                                           &lt;               &lt; v
        ///95 64                 v                                                                             &lt;
        ///17 47 82                                                                 &gt; $v
        ///18 35 87 10           &gt;00g2-:10p20p&gt;10g20g1+g10g20g2+g:10g1+20g2+g -:0`&gt;#^_-&gt;+10g20g1+p10g:1-10p#v_20g:1-:20p10p#v_01g.@
        ///20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_018 {
            get {
                return ResourceManager.GetString("Euler_Problem_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v303232332323
        ///v313232332323
        ///6
        ///&gt;2*&gt;::0g&quot;0&quot;-47*+\0p::v
        ///   |:-1p1\+*74-&quot;0&quot;g1 &lt;
        ///v $&lt;
        ///&gt;202p112p122p&quot;2&amp;&quot;*1+32p092pv
        ///v20+1g20p29+g29!+-1g21%7g20&lt;&gt;#       0# v#   &lt;      &gt;                 &gt;v
        ///&gt;p12g1+12p32g4%             |       &gt;1 &gt;&gt;22g\g12g1--|
        ///                            &gt;32g&quot;d&quot;%|  0^ &lt;  #      &gt;112p22g:1+22p66+-| 
        ///                          v%*4&quot;d&quot;g23&lt;&gt;#^_1^  |-+1*&quot;(2&quot;g23&lt;p23+1g23p221&lt; 
        ///                          &gt;          ^&gt;1^    &gt;92g.@      ^             &lt;.
        /// </summary>
        internal static string Euler_Problem_019 {
            get {
                return ResourceManager.GetString("Euler_Problem_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        ///v0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
        ///&gt;&quot;d&quot;&gt;1-:!#v_:03p013p&quot;~I&quot;+23p&gt;23g&quot;d&quot;%1+23g&quot;d&quot;/g&quot;0&quot;-03g*13g+:55+%68 v
        ///    ^     $#               _^#!p32:-1g32p31/+55p/&quot;d&quot;g32+1%&quot;d&quot;g32+*&lt;
        ///          &gt;&quot;~I&quot;+33p0&gt;33g&quot;d&quot;%1+33g&quot;d&quot;/g&quot;0&quot;-+  33g:1-33p v
        ///                 @._^#!                                &lt;.
        /// </summary>
        internal static string Euler_Problem_020 {
            get {
                return ResourceManager.GetString("Euler_Problem_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///################################################################################################################################################################################################################################################################################################################################################################################################################
        ///########################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_021 {
            get {
                return ResourceManager.GetString("Euler_Problem_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;               v                                     &gt;   v
        /// MARY           &gt;&quot;??IE&quot;*++:20p00p&gt;010p0 &gt;:00gg&quot;@&quot;-:0`#^_$0&gt;10g74**+10pv
        /// PATRICIA                      &gt; ^      ^          _v#         -+66:+1&lt;
        /// LINDA                    v   _^#!p00:-1g00pg000g01$&lt;          &gt;v
        /// BARBARA                  &gt;20g30p&gt;       040p&gt; 040g1+g 040g2+g`|&gt;40g:1+&gt;60p70p66+:80p&gt;:60g1+g\70g1+g80g60g1+v
        /// ELIZABETH                                   |`\-1g03 p04:+1g04&lt;                   $&lt;|\p08:-1:g08p+1g07g08p &lt;
        /// JENNIFER        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_022 {
            get {
                return ResourceManager.GetString("Euler_Problem_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///################################################################################################################################################################################################################################################################################################################################################################################################################
        ///########################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_023 {
            get {
                return ResourceManager.GetString("Euler_Problem_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0123456789
        ///&gt;&quot;ddd&quot;**1v
        ///vp129p11-&lt;
        ///       &gt;v&gt;v     v     &lt;  v    &lt;   &gt;  v   &gt;\1-\vv    p14+1g14&lt;
        ///&gt;21g:1+|&gt;|&gt;21g0\&gt;:1-:#^_v&gt;*\:#^_$:|  &gt;31p 141p &gt;31g41g*11g`!|
        ///       $             &gt;$1 ^ &gt; p68*v&gt;$1^   |-&quot;x&quot; g0:\&lt;\1&lt;g14  &lt;
        ///       @ &gt;          #^0#&lt;#v0#,+ #&lt;$     v&gt;    &gt;1+\:|  1
        ///^p12-1g12p11-*-1g14g13g11 &lt;^\&quot;x&quot;\-&quot;0&quot;g0:&gt;#- #1 #$ #&lt;  ^.
        /// </summary>
        internal static string Euler_Problem_024 {
            get {
                return ResourceManager.GetString("Euler_Problem_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// 00000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000
        /// 00000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000
        /// 00000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000
        /// 00000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000
        /// 00000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_025 {
            get {
                return ResourceManager.GetString("Euler_Problem_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///####################################################################################################
        ///####################################################################################################
        ///####################################################################################################
        ///####################################################################################################
        ///####################################################################################################        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_026 {
            get {
                return ResourceManager.GetString("Euler_Problem_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v     // Project Euler - Problem 12
        ///
        ///
        ///####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_027 {
            get {
                return ResourceManager.GetString("Euler_Problem_027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;d&quot;55+*1+::1-01p*&gt;:01g-:01g-:01g-:01g-:1-#v_&gt;+\:#&lt;_$.@
        ///X                ^p10-2g10                &lt;.
        /// </summary>
        internal static string Euler_Problem_028 {
            get {
                return ResourceManager.GetString("Euler_Problem_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        /// #########################################################################################################################################################################################################
        /// #################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_029 {
            get {
                return ResourceManager.GetString("Euler_Problem_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                   &gt;55+/ v v    $$_v#!:-1               &lt;&lt;
        ///&gt;01&gt;::9::*:***0\&gt;:#&lt;|#\+1\&lt;&gt;9::*:***&gt;:::55+%::*:**\55+/v&gt;|:
        ///                    &gt;$ -#v_^&gt;$&gt;+\:#&lt;_vv/+55\**:*::%+55:&lt;-&gt;^
        ///   ^                   +1&lt;           $&gt;:55+%::*:**\55+/v+
        ///                                     .v/+55\**:*::%+55:&lt;+
        ///                                     @&gt;:55+%::*:**\55+/v+
        ///                                      v/+55\**:*::%+55:&lt;+
        ///                                      &gt;55+%::*:**\55+$++^.
        /// </summary>
        internal static string Euler_Problem_030 {
            get {
                return ResourceManager.GetString("Euler_Problem_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v#########
        /// ###
        ///
        ///&gt;00000000010p20p30p40p50p60p70p80p90p  &quot;d&quot;2*  11p921p031p 0v
        ///v                                                         $&lt;
        ///             vp0p12:+1g120&lt;  &gt;g25**+70g5*+80g2*+90g+v       
        ///&gt;21g0g1+21g0p&gt;21g9-       |&gt;10g5&quot;d&quot;**20g2&quot;d&quot;**+&quot;d&quot;3v&gt;:11g\`|
        ///p                         &gt;^ ^6+**45g05+*&quot;2&quot;g04+*g0&lt;v&lt;     
        ///^12-1&lt;                              v&lt;      v       &lt;|-g11 &lt;
        ///     |                           -1:&lt;|g0:g12&lt;p13+1g13&lt;
        ///     &gt;$31g.@                         &gt;1-21p ^.
        /// </summary>
        internal static string Euler_Problem_031 {
            get {
                return ResourceManager.GetString("Euler_Problem_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// $$$$$$$$$
        /// ###############################
        ///
        ///    vp2\0:&lt;
        ///&gt;&quot; &quot;&gt;  1-:|
        ///       v                                                                                                                                                 &lt;  *&quot;ce&quot;&lt;
        ///v   p01 1$&lt;       vp1\0:&lt;         &gt;v    &gt;v          &gt;$v         &gt;v    &gt;v          &gt;$v         &gt;v    &gt;v          &gt;$v   v\g1:&lt; &gt;10g:1+10p2pv
        ///&gt;9&quot;ec&quot;*&gt;80p:80g55+&gt;  1-:|  &gt;:55+%:|&gt;:1g!|&gt;1\1p55+/:!| &gt;\:&gt;:55+%:|&gt;:1g!|&gt;1\1p55+/:!| &gt;*:&gt;:55+%:|&gt;:1g!|&gt;1\1p55+/:!| &gt;55+&gt; 1-:|&gt;|      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_032 {
            get {
                return ResourceManager.GetString("Euler_Problem_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;110p120p&quot;cc&quot; v
        ///vp09p08       &lt;     &gt;80g55+/90g55+/-#v_v                           
        ///&gt;90g80g`!#v_&gt;80g55+/|                  &gt;80g90g55+/*90g80g55+/*-#v_v
        ///            v       &lt;                &lt;                          &lt;
        ///                    &gt;80g55+/90g55+%-#v_v
        ///            &gt;80g55+/|                  &gt;80g90g55+/*90g80g55+%*-#v_v
        /// @v\p05:&lt;   v       &lt;                &lt;                          &lt;  
        /// .&gt;50g%:|: &lt;        &gt;80g55+%90g55+/-#v_v
        /// ^/\g02$&lt;  g&gt;80g55+%|                  &gt;80g90g55+%*90g80g55+/*-#v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_033 {
            get {
                return ResourceManager.GetString("Euler_Problem_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;1:00p1*:10p2*:20p3*:30p4*:40p5*:v
        ///vp110$p09:*9p08:*8p07:*7p06:*6p05&lt;
        ///      v_v#                          :-1&lt;p11 &lt;
        ///&gt;90g7*&gt;::0\&gt;:55+%0g\55+/:#v_&gt;+#&lt;\:#&lt;_+-|    +
        ///    &gt;3-.$@ |:/+55\g0%+55: &lt;            &gt;:11g^
        ///    ^g11&lt;  &gt;                ^.
        /// </summary>
        internal static string Euler_Problem_034 {
            get {
                return ResourceManager.GetString("Euler_Problem_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v          // Project Euler - Problem 35
        ///
        ///
        ///################################################################################################################################################################################################################################################################################################################################################################################################################################################################################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_035 {
            get {
                return ResourceManager.GetString("Euler_Problem_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v      
        ///0             v                      \&lt;     v            *2\&lt;     &gt;:.55+,\   v
        ///&gt;093194*+**&gt;::&gt;55+*10p:55+%10g+\55+/:#^_$::0&gt;10p:2%10g+\2/:#^_$-!#^_$        v
        ///           |:-1                                                              &lt;
        ///v          &lt;     v                      \&lt;     v            *2\&lt;     &gt;:.55+,\v
        ///&gt;93194*+**&gt;::55+/&gt;55+*10p:55+%10g+\55+/:#^_$::0&gt;10p:2%10g+\2/:#^_$-!#^_$     v
        ///          |:-1                                                               &lt;
        ///          &gt;&quot;= &quot;,,&gt;+\:#&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_036 {
            get {
                return ResourceManager.GetString("Euler_Problem_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v          // Project Euler - Problem 37
        ///
        ///
        ///################################################################################################################################################################################################################################################################################################################################################################################################################################################################################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_037 {
            get {
                return ResourceManager.GetString("Euler_Problem_037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v#########
        ///v#########    v                                                                                                                                              &lt;#     p145&lt;
        /// #########         v          +1&lt;           v            &lt;  v               &lt;                 vp2\0:&lt;         &gt;v    &gt;v          &gt;$v   v\g2:&lt;
        ///&gt;&quot;ec&quot;*31p&gt;241p&gt;01-1&gt;:31g*\:41g-#^_$&gt;\10p01-\&gt;:55+%\55+/:#^_$&gt;10g55+*+10p:1+#^_$10g\:1+#v_$:55+&gt;  1-:|  &gt;:55+%:|&gt;:2g!|&gt;1\2p55+/:!| &gt;55+&gt; 1-:|&gt;#v_$41g1-:41p1-#^_31g1-:31p|
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_038 {
            get {
                return ResourceManager.GetString("Euler_Problem_038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;010p020p630p&quot;d&quot;55+*90p050p30g3/70p         v
        /// vp07/3g03p050                                                    p03+2&lt;
        ///v                     &gt;#        v# p07-1&lt;           &gt;10p30g20pv
        ///&gt;30g::270g*-*\70g-2*%#^_50g1+50p&gt;70g:2-#^_$50g:10g`#^_$       &gt;30g:90g-|
        /// &gt;                             $^$          &lt;                    @.g02$&lt;.
        /// </summary>
        internal static string Euler_Problem_039 {
            get {
                return ResourceManager.GetString("Euler_Problem_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;01:55+*:55+*:55+*:55+*:55+*:55+*130p v
        ///         v                                           &lt;
        ///&gt;110p120p&gt;:10g920g**`!#v_10g920g**-10g1+10p20g55+*20p^&gt;v          &lt;
        ///  &gt;30g.@               &gt;1-:10g/20g+\      10g%10g\-1-:|&gt;\55+/\1-:#^_v
        ///  $                                   $               &gt;           :^
        ///^_^#:                                 &lt;#                p03*g03%+55$&lt;.
        /// </summary>
        internal static string Euler_Problem_040 {
            get {
                return ResourceManager.GetString("Euler_Problem_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXXXXX
        ///vXXXXXX
        ///$
        ///&gt;7  12p 0&gt;:0\1p::&quot;1&quot;+v     
        ///         |-g21:+1p0\ &lt;
        ///v   p231$&lt;
        ///              &gt;32g1gv
        ///        &gt;32g2%| vp24&lt;&gt;2g1g1+32gv 
        ///&gt;32g:1g`|     &gt;0    ^^3p0g23p0&lt;1
        ///^       &gt;032g1pv&gt;42g0g32g0g42g^p
        ///^p23+1g23      &lt;          vp230&lt;
        ///     v6:-1g26*+ 55&lt;0p26g21&lt;          @.&lt;
        ///     &gt;2p0g&quot;0&quot;-+62g|                    $
        ///               #  &gt;:&gt;302pv &gt;:02g2-:*` !|
        ///               $    &gt;!\2% +|%p20+1:g20:&lt;
        ///                    ^`2::&lt; $  
        ///               ^           &lt;.
        /// </summary>
        internal static string Euler_Problem_041 {
            get {
                return ResourceManager.GetString("Euler_Problem_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                               v ################################################################################
        ///                                ################################################################################
        ///A                               ################################################################################
        ///ABILITY                         ################################################################################
        ///ABLE                            ######################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_042 {
            get {
                return ResourceManager.GetString("Euler_Problem_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXXXXXXXX
        ///vXXXXXXXXX
        ///
        ///&gt;902p012p9&gt;:0\1pv
        ///          |\-1: &lt;
        ///&gt;12g55+, #$ &quot; =&quot;,, . @                                       vp20&lt;
        ///|`9g20    &lt;                                                  &lt;  &lt;
        ///             &gt;$0v        &gt; v                         &gt;002g0g&quot;0&quot;-1p v
        ///&gt;02g0g&quot;0&quot;-:9`|  &gt;:22p55+-| &gt;22g1g     #v_ 02g0g&quot;9&quot;`!#^_         ## v
        ///             &gt;1+^        &gt;0|-9p22+1:g22&lt;vp20-1g20p0g20+&quot;0&quot;g22p1g221&lt;
        ///v!`g200                                 &lt;             p20+1g20&lt; ##
        ///                           &gt;  02g0g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_043 {
            get {
                return ResourceManager.GetString("Euler_Problem_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;v%%% %%%%       &gt;    v
        ///v06p09:/2*-1*3:p06::+1&lt;vg07g09                         &lt;&lt;  &lt;
        ///g$ &gt;:70p:3*1   v #      &gt;0v&gt;vv p03+g03*2:p04-\g04+g03:&lt;
        ///v                      &lt;3 pp2# v/4    &lt;   &gt;:30g+40g`! |
        ///1#  &gt;            4**1+:0^ 40&gt;0g&gt;:40g`#^_&gt;:|:/4p03/2g03&lt; $
        ///&gt;-:|^6-p08:/2*-&lt; #        &gt;^ &gt;30g2/30p4/^ &gt;$30g:*-30g\  |
        /// 8 &gt;$$           ^v030:+1**46+g09g08             &gt;# !#  # _^
        /// &gt;::**::**8*20p1 ^v&gt;vv p03+g03*2:p04-\g04+g03:&lt;@.-g08g0 9&lt;
        ///                  pp2# v/4    &lt;   &gt;:30g+40g`! |  ^5%6   &lt;$
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_044 {
            get {
                return ResourceManager.GetString("Euler_Problem_044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                 &gt;v
        ///&gt;8::**::**8*:*20pv0v&gt;vv p03+g03*2:p01-\g01+g03:&lt;
        ///v           +&quot;l#&quot;&lt;3pp2# v/4    &lt;   &gt;:30g+10g`! |
        ///&gt;1+::2*1-*64**v   010&gt;0g&gt;:10g`#^_&gt;:|:/4p03/2g03&lt;
        ///^        &lt;  $&lt;&gt;1+:^&gt;^ &gt;30g2/30p4/^ &gt;$30g:*-v
        ///@.*-1*2:_^#!_^#!                    -5%6g03&lt;.
        /// </summary>
        internal static string Euler_Problem_045 {
            get {
                return ResourceManager.GetString("Euler_Problem_045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v##### ### // Project Euler - Problem 46
        ///########################################################################################################################################################################################################
        ///########################################################################################################################################################################################################
        ///################################################################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_046 {
            get {
                return ResourceManager.GetString("Euler_Problem_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v          // Project Euler - Problem 47
        ///
        ///
        ///################################################################################################################################################################################################################################################################################################################################################################################################################
        ///################################################################ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_047 {
            get {
                return ResourceManager.GetString("Euler_Problem_047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v   v0p01**&lt;  &gt;:30p::&gt;20p\1-:  #v_$$v
        ///5&gt;8#&lt;&quot;}&quot;* #*&gt;:|      ^%g01*g02:\&lt;   2
        ///&gt;5+:::*:*: ^^-&gt;# $# .# @#1g03%g01+g0&lt;.
        /// </summary>
        internal static string Euler_Problem_048 {
            get {
                return ResourceManager.GetString("Euler_Problem_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v?&gt;:55+%2+\55+/:5v&gt;&quot;Z%&quot;v&gt;+\55+/:55v&gt;v v           0`*&quot;ce&quot;:+*&quot;Z%&quot;$&lt;
        ///&quot; :v55:/+55\+2%+5&lt;\  v&lt;*2v+55\+2%+&lt;:v&gt;$:.48*,&quot;Z%&quot;*+:.48*,&quot;Z%&quot;*+. @
        ///( :&gt;+%2+\55+/2+***^  01+%/&gt;* -#v_-!|:|&lt;                          #
        ///%   v5:/+55\+2%+55::g&lt;:1+2*    v   &lt;&quot;&gt;::2%!#v_v &gt;10g\%!#v_:10g2/`|
        ///&quot;   &gt;5+%2+\55+/:55v   p05+*    $   ve#&lt; v%3:&gt;#&lt;#^ #&lt;    &gt;    v   :
        ///* +v***+2/+55\+2%+&lt;   ^&lt;5&gt;^    $    c`  &gt; !#^_10p7:^:+6_^#%\g01-2&lt;
        ///7 1&gt;\&quot;Z%&quot;*+:55+%2+\55+/:^      v   &lt;&quot;*^                   $$$&lt;
        ///&gt;+^                            &lt;    &gt;^.
        /// </summary>
        internal static string Euler_Problem_049 {
            get {
                return ResourceManager.GetString("Euler_Problem_049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v          // Project Euler - Problem 50
        ///###################################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_050 {
            get {
                return ResourceManager.GetString("Euler_Problem_050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;c&quot;02p                v &gt;02g1+::02p 2%!#v_5%!#v_312p&gt;12g1+:12p27*-!#v_022pv&gt; v
        ///##############        &gt;#|v#-*8&quot;}&quot;g20&lt;   $           ^                &lt; &gt;1#0|
        ///OOO OO OOO   #        ^ @# &gt;#       ^#  &lt;     &lt;                     &lt;^_^#&lt;1&gt;v
        ///##############                                              &gt;22g1+:22p3-!^2#
        ///110001#??????#         &gt;                                    ^               &lt;
        ///101001#??????#           &gt; ^v24 pg21+7\+&quot;0&quot;%+55g24:&gt;#&lt;:      !#v_ v       g+
        ///100101#??????#              &gt;g55+/42p&gt;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_051 {
            get {
                return ResourceManager.GetString("Euler_Problem_051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55+&gt;v&gt;v&gt;5+/&gt;::103p55+*&gt;55+/        :#v_$212pv
        ///XX  :6/5 &gt;  ::103p55+*^p30*g30+2%+55:&lt;      :
        ///XX  0:1:  v$_v#!:       /+55&lt;*+55p311* &lt;g21 &lt;
        ///XX  1p1p  1  &gt;:55+%2+13g*13p^     &gt;:12g^
        ///  &gt;^&gt;^&gt;^  &gt;3g03g-   #v_12g1+:12p7-|
        ///  ^*+55$_^#!`\g11:+1$&lt;        @$$.&lt;.
        /// </summary>
        internal static string Euler_Problem_052 {
            get {
                return ResourceManager.GetString("Euler_Problem_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v ###    ####################################################
        ///         ####################################################
        ///&gt;190p191p020p130pv                 &gt;40g9+30g2%!g40g8+30g2%!g+vv!g!%2g03+9g04`**&lt;
        ///&gt;30g:&quot;d&quot;-!#v_1+:30p2/40p&gt;30g40g2*&gt;-|                         &gt;:40g9+30g2%p&quot;}}@&quot;^
        ///^          &gt;#&lt;$ #&lt;20g.@            &gt;40g8+30g2%!g2*           ^&gt;$40g9+1-30g2%!g!v
        ///                      &gt;30g40g2* -^v                                _v#!_v#!_v#!&lt;
        ///             ^       _^#!p04:-1g04&lt;p%2g03+9g040p02++1!!-*2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_053 {
            get {
                return ResourceManager.GetString("Euler_Problem_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;096p&quot;~&quot;8*1+04p906p036p 116p   v 
        ///
        ///###############
        ///
        ///$
        ///$  $
        ///$$ $$$$$ $
        ///$$
        ///
        ///8C TS KC 9H 4S 7D 2S 5D 3S AC  
        ///5C AD 5D AC 9C 7C 5H 8D TD KS    
        ///3H 7H 6S KC JS QH TD JC 2D 8S  
        ///TH 8H 5C QS TC 9H 4D JC KS JS               &gt;&quot;A&quot;v
        ///7C 5H KC QH JD AS KH 4C AD 4S  &gt;36g06gg36g3%|
        ///5H KS 9C 7D 9H 8D 3S 5D 5C AH               &gt;&quot;0&quot;-55+\:89+-!#v_:39*-!#v_:&quot;!&quot;-!#v_ :892*+-!#v_:66*-!#v_\$v
        ///6H 4H 5C 3H 2H 3S QH 5S 6S AS                   &gt;          v&gt;$1+    0&gt;$1+    0&gt;$1+       0&gt;$1+    0&gt;$1+v
        ///TD 8C 4H 7C TC KC  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_054 {
            get {
                return ResourceManager.GetString("Euler_Problem_054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                           v-1\+g02&lt;
        ///0          v/+55\+g01\p01%+&lt;        $  v/+55\+g01\p01%+&lt;
        ///&gt;&quot;}P&quot;*&gt;::0\&gt;:!#v_\55+*\:55 ^&gt;:!#v_\::0\&gt;:!#v_\55+*\:55 ^
        ///    &gt;$ .@      &gt;$+38*   #v  ^#   &lt;  |-p02:$&lt;
        ///    ^_^#!:-1             &lt;\+1\$$&lt;^$$&lt;.
        /// </summary>
        internal static string Euler_Problem_055 {
            get {
                return ResourceManager.GetString("Euler_Problem_055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXX ######################################################################
        /// XXX ######################################################################
        ///     ######################################################################
        ///
        ///&gt;        &quot;c&quot;v  _v#   `*95:&lt;
        ///v+&quot;I~&quot;&lt;\&quot;c&quot;:&lt;       &gt;:55+%|
        ///&gt;1-:0\:&quot;F&quot;%v    &gt;1-:|:-1  &lt;
        ///|:p/&quot;F&quot;\+5 &lt;@.g1$#2$&lt;
        ///&gt;$188*2p020p10p&gt;030p&quot;~J&quot;+&gt;1-:::&quot;F&quot;%5+\&quot;F&quot;/g10g*20g+:55+/v
        ///     &gt;21p &gt; 1-:|^$&lt;      |:p/&quot;F&quot;\+5%&quot;F&quot;:\p03+g03:%+55p02&lt;
        ///     ^g03_^#`g1&gt;# ^#2g03$&lt;.
        /// </summary>
        internal static string Euler_Problem_056 {
            get {
                return ResourceManager.GetString("Euler_Problem_056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///
        /// ###############################################################################
        /// ###############################################################################
        /// ###############################################################################
        /// ###############################################################################
        /// ###############################################################################
        ///
        /// ###############################################################################
        /// ############ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_057 {
            get {
                return ResourceManager.GetString("Euler_Problem_057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v####
        ///v##
        ///v#
        ///v###     &gt;             &gt;             &gt;      &gt;$0v  
        ///                &gt;             &gt;              $1v  
        ///  &gt;::2\`#^_:2-!#^_:2%!#^_:9\`#^_:3%!#^_:5%!#^_1 :v
        ///2&gt;^&lt;v\                      p21:+1g21:_v#-3 &lt;p2 1&lt;
        ///1  p&gt;:11p1-0\&gt;:2% !#v_v    v ++!!+1-g&lt; #    ^ &lt; &gt;v
        ///3  3         ^\+1\/2&lt; \    &gt;3-#v_$$  1&gt;12g\  !|&gt;|
        ///p 31 vp01p03p04 g11p12&lt;        &gt;:*11v1 &gt;$1   #$^
        ///1 p+ &gt;120pv        v%g04*&lt;v-1\    %g&lt;^ \!!-1:&lt;$0
        ///2 32 vg030&lt;  v-1\  &lt; &gt;10g^   &gt;\:::*11  g%1-!\^&gt;^
        ///3 3g     &gt;$1\&gt; :#v_ $ 21g &gt;:#^_$1-! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_058 {
            get {
                return ResourceManager.GetString("Euler_Problem_058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v###    0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ################################################################################################################################
        /// ### ## 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ################################################################################################################################
        /// ###    00000000000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_059 {
            get {
                return ResourceManager.GetString("Euler_Problem_059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXXX  /######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_060 {
            get {
                return ResourceManager.GetString("Euler_Problem_060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v$$  ### ---------------------------------------------------------------- ###
        /// $$  ### ---------------------------------------------------------------- ###
        /// $   ### ---------------------------------------------------------------- ###
        /// $   ### ---------------------------------------------------------------- ###
        /// $   ### ---------------------------------------------------------------- ###
        ///     ### ---------------------------------------------------------------- ###
        ///     ### ----------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_061 {
            get {
                return ResourceManager.GetString("Euler_Problem_061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v $ #####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
        ///  $ # [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_062 {
            get {
                return ResourceManager.GetString("Euler_Problem_062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v XXXX   #######################################################################
        ///  XX
        ///                          v1\1p12::+1   \+g2&lt;
        ///0                 v9p03p02&lt;         \g12:+1&lt;^2\p22_v
        ///1          &gt;v     v              &lt;  v-\&quot;P&quot;&lt;       :$
        ///&gt;        :v1v&gt;0p&gt;9&gt;:&quot;0&quot;\0p1+:&quot;O&quot;-|&gt;:0g&quot;0&quot;-||!`g12&lt;-$
        ///          :p\3v p050p04&quot;O&quot;&lt;p0\&quot;1&quot;&lt;^+&gt;#1 $#&lt; :21g-|\.
        ///          211p&gt; 40g0g&quot;0&quot;-2 0g*50g+:55+%&quot;0&quot;v&gt;$55+0v+@
        ///          &gt;^20|-8p04:-1g04 p05/+5 #5p0g04+&lt;&gt;5#$5#&lt;^
        ///            &gt;^&gt;30g1-:30p #^_9     ^.
        /// </summary>
        internal static string Euler_Problem_063 {
            get {
                return ResourceManager.GetString("Euler_Problem_063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v###
        /// #####
        ///0
        ///&quot;&gt;&gt;1-:0\951p11p021p131v      v12g14    p150 p13/g&lt;
        ///I       vp01g03_v#-g01:_v#- &lt;&gt;g+31g/ :31g*21g-21v1
        ///i   @   &gt;:30p:20 g\/+2/: 30g^^12p14:&lt;&gt;11g21g:*-3 ^
        /// *  .           &gt;    #$ &gt;$30g::*11g-||+g15-1g13p&lt;
        ///&quot;+  $   ^p02:p010g11p1&lt;       v\+1\&lt;&gt;&gt;0&gt;\#+ #1:#$_v
        ///&gt;^^_^#-2:                     &lt;   _^#          %2$&lt;.
        /// </summary>
        internal static string Euler_Problem_064 {
            get {
                return ResourceManager.GetString("Euler_Problem_064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v $$$    #######################################################################
        ///
        ///         #######################################################################
        ///
        ///    v                 -1&lt;
        ///&gt;&quot;F&quot;&gt;:9+&quot;0&quot;\0p:9+&quot;0&quot;\2p:|
        ///v&quot;c&quot;p040p2&quot;O1&quot;p0&quot;O0&quot;   $&lt;
        ///          &gt;$1         v@.&lt;v02-&quot;0&quot;p0g03:g2g03-&quot;0&quot;g0:p03:&lt;-1&lt;
        ///  &gt;:1-3%:!|   &gt;:1+3/2*v  +&gt;g*+40g+:55+%&quot;0&quot;+30g2p55+/40p:9-|
        ///&gt;:|       &gt;2-#^_1     &gt;20 p                      &quot;O&quot;v  #  $
        ///| &gt;# #+ #1 #: #- #12# ^#                            &gt;# ^# &lt;
        ///$               &gt;\v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_065 {
            get {
                return ResourceManager.GetString("Euler_Problem_065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vYYY     ################
        /// XBXX    ################
        /// ZZZ     ################
        /// N
        /// OOO     ################
        ///         ################
        ///         ################
        ///         ################                           v 9::p4+9\g5+9::p1+9\g2+9: &lt;
        ///         ################                           &gt;+6g\9+5p:1-\!v0  &lt;
        ///         ################                               v        $_::9+1g\9+0p:^
        ///                                 v  _v#-*&quot;}&quot;8p13:+1g13$&lt;              #     &lt;
        ///&gt;&quot;@ &quot;:*:**21p331p013p88 +&gt;:8+0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_066 {
            get {
                return ResourceManager.GetString("Euler_Problem_066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &gt;&quot;d&quot; 00p00g1-20p010p&gt;10g3*:20g1+g&quot;0&quot;-55+*\1+20g1+g&quot;0&quot;-+10g20g1+p10g1+:10p20g-1-#v_20g:1-20p010p#v_v
        ///59                    ^                                                           &lt;               &lt; v
        ///73 41                 v                                                                             &lt;
        ///52 40 09                                                                           &gt; $v
        ///26 53 06 34           &gt;00g2-:10p  20p &gt; 10g20g1+g  10g20g2+g  :  10g1+20g2+g -:0`&gt;#^_-&gt; + 10g20g1+ p   10g:1-10p#v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_067 {
            get {
                return ResourceManager.GetString("Euler_Problem_067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v  X   X ##########
        ///     X   OOOOOOOOOO
        ///&gt;&quot;:&quot;v   v                           &lt; &lt;
        ///v   &lt;   vp1+9-&quot;0&quot;g0+9p03:-1g03&quot;O&quot;    &lt;
        ///&gt;90p030p&gt;30g9+0g1-:30g9+0p&quot;0&quot;-:70p0\`|
        ///v   g03_^#!         -&quot;O&quot;g1+9g07     #&lt;$
        ///&gt;:#v_70g5`                           &gt;|
        ///v-1&lt; v  _v#!`g039$                    &lt;
        ///&gt;:#v_     70g9-!                     ^
        ///v-1&lt;     &gt;&quot;X&quot;70g9+1p&quot;:&quot;30g1+:30p9+0p^
        ///&gt;:#v_ 90+0g91+0g92+0g++51p70g9-!     ^
        ///v-1&lt; &gt;91+0g&quot;/&quot;- 98+0g&quot;/&quot;- 99+0g&quot;/&quot;- v
        ///&gt;:#v_90g&quot;0&quot;-70g`                     ^
        ///v-1&lt; v-&quot;/&quot;g0+79 -&quot;/&quot;g0+69 -&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_068 {
            get {
                return ResourceManager.GetString("Euler_Problem_068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v000000    // Project Euler - Problem 69
        ///################################################################################
        ///################################################################################
        ///################################################################################
        ///v                     &gt;p50g1+50pv                                         @.g07&lt;
        ///v                     ^1g0&lt;     &gt;30g1+:30p40g-       #v_&quot;}}@&quot;**60p   0&gt;:1g70g*v$
        ///&gt;170p&quot;P&quot;:10p3:20p*40p230pv^5g03_^#-&quot; &quot;g+1/g01\%g01:g03&lt;p050p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_069 {
            get {
                return ResourceManager.GetString("Euler_Problem_069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v00000 000 // Project Euler - Problem 70
        /// ccc
        /// ?? ?? ??
        ///######################################################################################################################################################
        ///######################################################################################################################################################
        ///##################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_070 {
            get {
                return ResourceManager.GetString("Euler_Problem_070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v X X C
        ///  X X ????
        ///
        ///&gt;020p040p121p141p&quot;}}@&quot;**60pv
        ///v0                         &lt;         &gt;01+*v
        ///&gt;1+ :3*7%!#v_:61p:3*7/:71p7*61g3*-:0`|    &gt;81p61g7*91p41g91g*21g81g*`#v_v
        ///|-g06:     &lt;                        &lt;&gt;01-*^v  p04g16p02g17p12g19p14g18&lt;
        ///&gt;$20g.&quot;/ &quot;,,55+,40g.@               ^      &lt;                            &lt;.
        /// </summary>
        internal static string Euler_Problem_071 {
            get {
                return ResourceManager.GetString("Euler_Problem_071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v00000     // Project Euler - Problem 72
        /// XX     |AAAAAAAAAAAAAAAAAAA|
        /// OOOO
        ///################################################################################################################################################################################################################################################################################################################################################################################################################################################ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_072 {
            get {
                return ResourceManager.GetString("Euler_Problem_072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v          // Project Euler - Problem 73
        /// XX  ????
        ///
        ///######################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_073 {
            get {
                return ResourceManager.GetString("Euler_Problem_073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v      X ##########            // Project Euler - Problem 74
        /// CCC
        /// XXXX   |------------------------------------------------------------|
        ///
        ///################################################################################################################################################################################################################################################################################################################################################################################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_074 {
            get {
                return ResourceManager.GetString("Euler_Problem_074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v XX  O OO // Project Euler - Problem 75
        ///  AAA A A
        ///
        ///######################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_075 {
            get {
                return ResourceManager.GetString("Euler_Problem_075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v  X OO    // Project Euler - Problem 76
        ///v
        ///v
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_076 {
            get {
                return ResourceManager.GetString("Euler_Problem_076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v00000 00  // Project Euler - Problem 77
        /// XXXXXX
        ///#####################################################################################################
        ///
        ///#####################################################################################################
        ///#####################################################################################################
        ///#####################################################################################################
        ///############################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_077 {
            get {
                return ResourceManager.GetString("Euler_Problem_077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXX OOO
        /// ##########################################################################################################################################################################################################################################################
        /// #                                                                                                                                                                                                                                                         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_078 {
            get {
                return ResourceManager.GetString("Euler_Problem_078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// ++++++++++ 319 680 180 690 129 620 762 689 762 318
        /// ++++++++++ 368 710 720 710 629 168 160 689 716 731
        /// ++++++++++ 736 729 316 729 729 710 769 290 719 680
        /// ++++++++++ 318 389 162 289 162 718 729 319 790 680
        /// ++++++++++ 890 362 319 760 316 729 380 319 728 716
        /// ++++++++++
        /// ++++++++++ ##########
        /// ++++++++++
        /// ++++++++++ XXXXXXXXXX
        /// ++++++++++
        ///
        ///&gt;55+&gt;:1\:v&gt;:55+/1+30p:55+%4*66++20p020g0+30gg&quot;0&quot;-:50p66v
        ///    |:-1p&lt; v1g070p+1g07+1g062p+1g07+1g052p+1g06+1g052&lt; +
        ///    &gt;$ 77*^&gt;+50g1+p070g1+60g1vv&lt;        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_079 {
            get {
                return ResourceManager.GetString("Euler_Problem_079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v X X XX X
        ///         ############################################################
        ///
        /// @       ############################################################
        /// .
        /// g       ############################################################
        /// 0
        /// ^9$&gt;# #&lt;         v             v               &lt;   v    &lt;
        ///    $ v_^#-&quot;d&quot;\+1:&lt;       &lt;&gt;$&quot;&lt;&quot;&gt;1-::9+5g\9+1p:#^_$0&gt;:::9+3g55+%55+*v
        ///&gt;090p2&gt;:20p&quot;d&quot;&gt;::*20g-#v_$^|!:-1p5+8\-g07g06p04          #         &lt;\
        ///    #  v&quot;&lt;&quot;:$_^#   !:-1&lt;   &gt;::9+1g40g-60p:9+3g20g45***70p0&gt;70g60g`!|5
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_080 {
            get {
                return ResourceManager.GetString("Euler_Problem_080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                                                                                                   4445 2697 5115 0718 2209 2212 0654 4348 3079 6821 7668 3276 8874 4190 3785 2752 9473 7817 9137 0496 7338 3434 7152 4355 4552 7917 7827 2460 2350 0691 3514 5880 3145 7633 7199 3783 5066 7487 3285 1084 8985 0760 0872 8609 8051 1134 9536 5750 9716 9371 7619 5617 0275 9721 2997 2698 1887 8825 6372 3014 2113 7122 7050 6775 5948 2758 1219 3539 0348 7989 2735 9862 1263 8089 6401 9462 3168 2758 3748 5870 
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_081 {
            get {
                return ResourceManager.GetString("Euler_Problem_081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                                                                                                   4445 2697 5115 0718 2209 2212 0654 4348 3079 6821 7668 3276 8874 4190 3785 2752 9473 7817 9137 0496 7338 3434 7152 4355 4552 7917 7827 2460 2350 0691 3514 5880 3145 7633 7199 3783 5066 7487 3285 1084 8985 0760 0872 8609 8051 1134 9536 5750 9716 9371 7619 5617 0275 9721 2997 2698 1887 8825 6372 3014 2113 7122 7050 6775 5948 2758 1219 3539 0348 7989 2735 9862 1263 8089 6401 9462 3168 2758 3748 5870 
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_082 {
            get {
                return ResourceManager.GetString("Euler_Problem_082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                                                                                                   4445 2697 5115 0718 2209 2212 0654 4348 3079 6821 7668 3276 8874 4190 3785 2752 9473 7817 9137 0496 7338 3434 7152 4355 4552 7917 7827 2460 2350 0691 3514 5880 3145 7633 7199 3783 5066 7487 3285 1084 8985 0760 0872 8609 8051 1134 9536 5750 9716 9371 7619 5617 0275 9721 2997 2698 1887 8825 6372 3014 2113 7122 7050 6775 5948 2758 1219 3539 0348 7989 2735 9862 1263 8089 6401 9462 3168 2758 3748 5870 
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_083 {
            get {
                return ResourceManager.GetString("Euler_Problem_083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v   XX
        ///  ========================================    v      &lt;     v&lt;
        ///  ???????????????????????????????????????? v&lt;&lt;   v&lt;&lt;&lt;|-&quot;!&quot;:&lt;|-+98:&lt;
        ///&gt;040p&quot;}}@&quot;**58*v             v   _v# -1&lt;  v&lt;10   v 10&gt; v    &lt;    &lt;|&lt;
        ///   v           &lt;                  0    |:+&lt;2?^#*4&lt;2?^#$&lt;         ^&lt;
        ///   &gt;1-:2+0\1pv                            ^3&lt;    ^3&lt;               -
        ///   |:        &lt;     &gt;&gt;&gt;v &gt;&gt;&gt;v v&lt;         &gt;&gt;&gt;v   &gt;&gt;&gt;v    &gt;&gt;&gt;v        2
        ///v $&lt;               12 v 12 v #^p04&lt;+55$&lt;01 v   01 v    01 v &gt;v     :
        ///&gt;40g::2+1g1+\2+1p&gt;#^?3&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_084 {
            get {
                return ResourceManager.GetString("Euler_Problem_084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vX
        /// YY YY YY
        ///&gt;&quot;}}_!&quot;+**:10p11p051p071p&gt;10g71g`v
        ///     v*`g18g01`g14g15&lt;p18 g17p141_v
        ///v8g01_51g1+:51p71g+7   1p^   @.g12&lt;
        ///&gt;1g-:0\`#v_0&gt;-:11g`#v_11p41g5v
        ///&gt;*81g+81v&gt;0\^v+1g14$&lt;#0p12*g1&lt;
        ///^g17p14:&gt;# p#&lt;       ^.
        /// </summary>
        internal static string Euler_Problem_085 {
            get {
                return ResourceManager.GetString("Euler_Problem_085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v##### ##                                    &gt;       &gt;$30gv &gt;`#v_v
        ///&gt;&quot;}}@&quot;**50p040p0&gt;1+:v&gt;&gt;1-::*70g:*+v  vp01g03_^#-g01:_^#- &lt;: g  : :
        ///                    :+  v         &lt;  &gt;:30p:20 g\/+2/: 30g^* 0&gt;#1v2
        ///                    71 &gt;           &gt;#^ #p #0 2 #&lt;$      v   7gv+&lt;/
        ///                    0*  &gt;:88*%&quot;9&quot;`#^_:88+%:9`#v_:2-#v_v   2 :082g8
        ///                    p2      &gt;     &gt;     &gt;     &gt; #     &gt;$&gt;$0&gt;|80/0 
        ///                    0p |!-8_^#-7:_^#-6:_^#-5:_^# -3:&lt;     g  +p7^&lt;
        ///                    80            &gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_086 {
            get {
                return ResourceManager.GetString("Euler_Problem_086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v000000000 
        ///################################################################
        ///################################################################################################################################################################################################################################################################################################################################################################################################################################################# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_087 {
            get {
                return ResourceManager.GetString("Euler_Problem_087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v XXXX
        ///  OOOO
        ///
        ///############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_088 {
            get {
                return ResourceManager.GetString("Euler_Problem_088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vABCDEFGHIJKLMNOPQRSTUVWXYZ
        ///v0123212342
        /// ????    ?
        ///&gt;092p190p5492*+0p55+v
        ///vp03&quot;d&quot;p0*62&quot;2&quot;p0*83&lt; &gt;::1g&quot;0&quot;-\v
        ///&gt;&quot;}&quot;4*40p&quot;}&quot;8*94+0p55+^_v#:-1p1 &lt;v+1       &lt;&gt;-*\ &gt;42p            22g+22pv
        ///                        &gt;$9:12p&gt;0&gt;:12gg48*-|^10\_^#`\g24::g0-&quot;@&quot;gg21:-1&lt;:
        ///                                           &gt;:32p 1-:12gg&quot;@&quot;-0g:42p22p&gt;:|&lt;
        ///                        v+55\g1 +1/+55%&quot;d&quot;:\g1+1/&quot;d&quot;%*8&quot;}&quot;:\/*8&quot;}&quot;:g22$&lt;
        ///MMMMDCLXXII             &gt;%1+1g\ +++32g\-92g+92pv
        ///MMDCCCLXXXIII                  |-+9*8&quot;}&quot;:p21:+1&lt;
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_089 {
            get {
                return ResourceManager.GetString("Euler_Problem_089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v X_XXOO #########                v6$&lt;                 &gt; #g #0 #+ #8 #: #:v#&lt;&gt;v
        ///2 X ##########v 2+4\1p22+g22!g2+4:&lt; _^#-9:%+55*:p1+4\1p12+g12!g1+4:/+55*::_v 1g
        ///9 X ##########v1+4\1p12+g12!g1+4:&lt;   _v#-9:%+55*:p2+4\1p22+g22!g2+4:/+55*::&lt; 26
        ///3  C          &gt;p                #^6$ #&lt;     #v      &gt;#      #&lt;           1-:|$`
        ///*&gt;020p8&gt;:0\9+0p:#v_$021p022p9&gt;:0\4+1p:0\4+2p:#v_$55+^vg0+9p0+9\!g0+9::::&lt;   &gt;^2
        ///+p     ^-1       &lt;^00       &lt;^-1              &lt;   v$$_!#v_1- #  #v #! #+^#`6g2&lt;
        ///33                         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_090 {
            get {
                return ResourceManager.GetString("Euler_Problem_090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2&quot;:11p031p41p&gt;11g51p51g1&gt; #1 #g #&lt;v
        /// X XXXX &gt;$41p#^_31g311g:**+.@&gt;$p v1+
        ///&gt;1g51g:61g-\*41g%!2*+31p61g1+61pv!56
        ///^  &gt;51g#^ #:1# - #1:#g5#11#4 ^#  _^1
        ///^3_^#!  +`g11g16`*:g14*-\g16:g15&lt; p&lt;.
        /// </summary>
        internal static string Euler_Problem_091 {
            get {
                return ResourceManager.GetString("Euler_Problem_091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v $$ T # #######################################################################
        ///       # #######################################################################
        ///  XX   # #######################################################################
        ///       # #######################################################################
        ///       # #######################################################################
        ///       # #######################################################################
        ///       # ########### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_092 {
            get {
                return ResourceManager.GetString("Euler_Problem_092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v XXXX   ####################################################################################################
        ///  XX     ####################################################################################################
        ///         ####################################################################################################
        ///  C      ####################################################################################################
        /// OOOO    ########################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_093 {
            get {
                return ResourceManager.GetString("Euler_Problem_093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;}}2( &quot;****04003pp201p102p&gt;04g01g2*`#v_v
        ///Xv2*2g10**!%3*g20-2g10!-1%3*g102`2g10&lt; 0
        ///X&gt;-*03g+03p01g2*3%2-!01g2+# 02g*3%v    3
        ///Xv*2g10+*2g20g10p30+g30*+* g1022*!&lt; @.g&lt;
        ///C&gt;02g3*+01p02p            ^.
        /// </summary>
        internal static string Euler_Problem_094 {
            get {
                return ResourceManager.GetString("Euler_Problem_094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v      # ####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_095 {
            get {
                return ResourceManager.GetString("Euler_Problem_095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v XX  X ###########  ###########  #############################        #############################                            003020600100920000000125400361025900020030090500400060000000080006080300000900002904200007
        /// C    C ###########  #         #  #                           #        #                           #                            900305001524010000008400000080960010000907000009000800800701040049070250050123400010000000
        /// PPPPP  ###########  #         #  #                           #        # [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_096 {
            get {
                return ResourceManager.GetString("Euler_Problem_096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;z~k&quot;+*7+98v@
        ///v +***&quot;Gqz&quot;&lt;.
        ///&gt;1- \2*&quot;(2&quot;v%
        ///|: \%*:** :&lt;*
        ///&gt;$1+&quot;(2&quot;:**:^.
        /// </summary>
        internal static string Euler_Problem_097 {
            get {
                return ResourceManager.GetString("Euler_Problem_097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXX #   #################################################################################################### #   A               ABILITY         ABLE            ABOUT           ABOVE           ABSENCE         ABSOLUTELY      ACADEMIC        ACCEPT          
        /// XXX #   #################################################################################################### #   ACCESS          ACCIDENT        ACCOMPANY       ACCORDING       ACCOUNT         ACHIEVE         ACHIEVEMENT     ACID            ACQUIRE    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_098 {
            get {
                return ResourceManager.GetString("Euler_Problem_098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v$$$$$$                                           519432,525806
        /// XX  00v         $&lt;                               632382,518061
        ///    v  &lt;p15g11p16_^#`g16:p&lt;                       78864,613712
        ///&gt;0:5 1p vv               &lt;1                       466580,530130
        /// v $ $  #&lt;v+1g12+*+55\p   12\-*86&lt;                780495,510032
        ///&gt;#  &gt; 0&quot;2&quot;&gt;:11gg:48*-0`!#^_:&quot;,&quot;- |                525895,525320
        ///^p110p16&lt; ^               # +1\0$&lt;                15991,714883
        ///   vp04+g04     &lt;   vp06&lt; +                       960290,50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Euler_Problem_099 {
            get {
                return ResourceManager.GetString("Euler_Problem_099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10v&gt;012p &gt;01g11g:01g3*\4*+01p3*\2*+11p02g12g:02g3*\4*-0v
        ///##1^p110&lt;|!`*:**&quot;@}}&quot;/4-g20-*g212-g10+*2g112p21-*2\*3p2&lt;
        ///##&gt;p102p^&gt;402g2*+12g2*+01g2*+11g2*-8/.@.
        /// </summary>
        internal static string Euler_Problem_100 {
            get {
                return ResourceManager.GetString("Euler_Problem_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Fibonacci Numbers
        /// * by Mike Schwörer 2014
        ///*/
        ///
        ///program Fibbonacci
        ///	begin
        ///		doFiber(1000);
        ///		
        ///		quit;
        ///	end
        ///	
        ///	void doFiber(int max)
        ///	var
        ///		int last := 0;
        ///		int curr := 1;
        ///		int tmp;
        ///	begin
        ///		repeat
        ///			if (last &gt; 0) then
        ///				out &quot;,&quot;;
        ///			end
        ///			
        ///			out curr;
        ///			
        ///			tmp = curr + last;
        ///			last = curr;
        ///			curr = tmp;
        ///		until (last &gt; max)
        ///	end
        ///end.
        /// </summary>
        internal static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0&quot;!dlroW olleH&quot;&gt;:#,_$@.
        /// </summary>
        internal static string example_compile {
            get {
                return ResourceManager.GetString("example_compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Language Name=&quot;Syntaxfile template&quot; Startblock=&quot;Code&quot;&gt;
        ///&lt;FileTypes&gt;
        ///	&lt;FileType Extension=&quot;.tf&quot; Name=&quot;TextFunge&quot;/&gt;
        ///&lt;/FileTypes&gt;
        ///
        ///	&lt;Block Name=&quot;Code&quot; Style=&quot;Code&quot; IsMultiline=&quot;true&quot;&gt;
        ///		&lt;Scope Start=&quot;&quot; End=&quot;&quot; Style=&quot;Scope&quot; Text=&quot;...&quot; /&gt;
        ///		
        ///		&lt;!-- Keywords that can exist inside this block --&gt;
        ///		&lt;Keywords&gt;
        ///			&lt;PatternGroup Name=&quot;Keywords&quot; Style=&quot;Keyword&quot; CaseSensitive=&quot;false&quot;&gt;
        ///				&lt;Patterns&gt;
        ///				program end begin var in out return if then while repeat else got [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFunge {
            get {
                return ResourceManager.GetString("TextFunge", resourceCulture);
            }
        }
    }
}
